### ISSUE TITLE
How to do this with Java 1.7 ? 

### ISSUE THREAD

**Issue by stanbar** [Zhuinden/realm-databind-experiment#1]
How to do this with Java 1.7 ? 
I can't do below 1.8 

    RealmDataBinding.Factory FACTORY = () -> element -> {
        if(element instanceof RealmDataBinding) {
            ((RealmDataBinding)element).notifyChange();
        }
    };

**Comment by Zhuinden** [comment]
That's actually just a shorthand for

``` java
        RealmDataBinding.Factory FACTORY = new RealmDataBinding.Factory() {
            @Override
            public RealmChangeListener create() {
                return new RealmChangeListener() {
                    @Override
                    public void onChange(Object element) {
                        if(element instanceof RealmDataBinding) {
                            ((RealmDataBinding)element).notifyChange();
                        }
                    }
                };
            }
        };
```

**Comment by stanbar** [comment]
OH, yea. Thanks. Btw. How to enable Java 1.8 ? I get the message that DataBinding is not supported by Jack compiler.

**Comment by Zhuinden** [comment]
Don't use Jack compiler it sucks, use Retrolambda

https://github.com/Zhuinden/realm-databind-experiment/blob/master/build.gradle#L13

https://github.com/Zhuinden/realm-databind-experiment/blob/master/app/build.gradle#L3

https://github.com/Zhuinden/realm-databind-experiment/blob/master/app/build.gradle#L10-L13

**Comment by stanbar** [comment]
Thank you very much !
