### ISSUE TITLE
Transient has been supported. What about now?!

### ISSUE THREAD

**Issue by Drjacky** [Zhuinden/realm-databind-experiment#2]
I read [your publication](https://medium.com/@Zhuinden/realm-1-2-0-android-data-binding-1dc06822287f) on Medium and I saw you mentioned this:

> You might not know, but a class that defines the Realm schema must either implement RealmModel and have @RealmClass annotation, or extend RealmObject.
> This also means you can’t extend BaseObservable easily, **because it has a transient field, and transient fields are not supported.**

On the other hand, I see this closed issue: [4436](https://github.com/realm/realm-java/pull/4436).
Honestly, I get confused! :confused: What is best practice code to work with `Realm` and `DataBinding` simultaneously?

P.S. If the best solution is using `transient ` nowadays, please explain with a snipped code. :pray:

**Comment by Zhuinden** [comment]
Transient is supported, but you still can't extend classes that aren't RealmObject, even if they only contain methods and transient/ignored fields.

**Comment by Drjacky** [comment]
Just write the model like `Product` model in this comment: [839](https://github.com/realm/realm-java/issues/839#issuecomment-352684755)
